packages:
  - '*/src'
catalog:
  '@antfu/eslint-config': ^3.11.2
  '@eslint/config-inspector': ^0.5.6
  '@iconify/collections': ^1.0.491
  '@iconify/json': ^2.2.280
  '@slidev/cli': ^0.50.0-beta.10
  '@slidev/client': ^0.50.0-beta.10
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^22.10.1
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  eslint: ^9.16.0
  eslint-plugin-format: ^0.1.3
  esno: ^4.8.0
  execa: ^9.5.1
  fast-glob: ^3.3.2
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.49.0
  pnpm: ^9.14.4
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^0.0.4
  taze: ^0.18.0
  typescript: ^5.7.2
  unocss: ^0.65.1
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vis-timeline: ^7.7.3
  vue-router: ^4.5.0
  vue-tsc: ^2.1.10
