packages:
  - '*/src'
catalog:
  '@antfu/eslint-config': ^6.0.0
  '@eslint-react/eslint-plugin': ^2.2.3
  '@eslint/config-inspector': ^1.3.0
  '@iconify/collections': ^1.0.609
  '@iconify/json': ^2.2.399
  '@slidev/cli': ^52.5.0
  '@slidev/client': ^52.5.0
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^24.9.1
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  eslint: ^9.38.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-format: ^1.0.2
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.24
  eslint-typegen: ^2.3.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.56.1
  pnpm: ^10.19.0
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^1.0.0
  taze: ^19.8.1
  tinyexec: ^1.0.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  unocss: 66.4.0
  uqr: ^0.1.2
  vis-data: ^8.0.3
  vis-network: ^10.0.2
  vis-timeline: ^8.3.1
  vite: ^7.1.12
  vue-router: ^4.6.3
  vue-tsc: ^3.1.1
onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - unrs-resolver
