packages:
  - '*/src'
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@eslint-react/eslint-plugin': ^1.52.6
  '@eslint/config-inspector': ^1.2.0
  '@iconify/collections': ^1.0.589
  '@iconify/json': ^2.2.379
  '@slidev/cli': ^52.1.0
  '@slidev/client': ^52.1.0
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^24.3.0
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  eslint: ^9.34.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-typegen: ^2.3.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.55.0
  pnpm: ^10.15.0
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^1.0.0
  taze: ^19.3.0
  tinyexec: ^1.0.1
  tsx: ^4.20.5
  typescript: ^5.9.2
  unocss: ^66.4.2
  uqr: ^0.1.2
  vis-data: ^8.0.1
  vis-network: ^10.0.1
  vis-timeline: ^8.3.0
  vite: ^7.1.3
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - unrs-resolver
