packages:
  - '*/src'
catalog:
  '@antfu/eslint-config': ^5.4.1
  '@eslint-react/eslint-plugin': ^2.0.6
  '@eslint/config-inspector': ^1.3.0
  '@iconify/collections': ^1.0.602
  '@iconify/json': ^2.2.392
  '@slidev/cli': 52.1.0
  '@slidev/client': 52.1.0
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^24.7.0
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  eslint: ^9.37.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-format: ^1.0.2
  eslint-plugin-react-hooks: ^6.1.1
  eslint-plugin-react-refresh: ^0.4.23
  eslint-typegen: ^2.3.0
  execa: ^9.6.0
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.55.1
  pnpm: ^10.18.0
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^1.0.0
  taze: ^19.7.0
  tinyexec: ^1.0.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  unocss: ^66.5.2
  uqr: ^0.1.2
  vis-data: ^8.0.3
  vis-network: ^10.0.2
  vis-timeline: ^8.3.1
  vite: ^7.1.9
  vue-router: ^4.5.1
  vue-tsc: ^3.1.0
onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - unrs-resolver
